### ISSUE TITLE
bug: SystemUI crashes with a floating app from LMOFreeform open

### ISSUE THREAD

**Issue by joshuah345** [RisingTechOSS/issue_tracker#58]
### Issue type

Feature not working as intended

### Device

Redmi Note 12 Pro 5G (rubyx)

### risingOS version

risingOS 6.x

### Exact version / Build date

6.0 - Dec 20 2024

### Bug description

With an app on screen from LMOFreeform, systemui crashes endlessly after locking then unlocking the device.

### Steps to reproduce

1. Enable the sidebar in personalization settings
2. Launch an app from the sidebar (or launch the app picker for it)
3. Lock device / Put device to sleep
4. attempt to unlock device

### Relevant log (logcat/build log)

```shell
12-24 13:24:40.748 23159 23159 E AndroidRuntime: FATAL EXCEPTION: main
12-24 13:24:40.748 23159 23159 E AndroidRuntime: Process: com.android.systemui, PID: 23159
12-24 13:24:40.748 23159 23159 E AndroidRuntime: java.lang.IllegalArgumentException: Receiver not registered: com.android.systemui.notifications.ui.PeekDisplayViewController$screenReceiver$1@dd13584
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1674)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1901)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:822)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:822)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at com.android.systemui.notifications.ui.PeekDisplayViewController.unregisterCallbacks(PeekDisplayViewController.kt:112)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at com.android.systemui.notifications.ui.PeekDisplayView.onDetachedFromWindow(PeekDisplayView.kt:296)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.view.View.dispatchDetachedFromWindow(View.java:22935)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3965)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3957)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3957)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3957)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3957)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDetachedFromWindow(ViewGroup.java:3957)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5581)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.view.ViewGroup.removeViewInternal(ViewGroup.java:5552)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.view.ViewGroup.removeView(ViewGroup.java:5483)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at com.android.systemui.shade.NotificationPanelViewController.reInflateViews(NotificationPanelViewController.java:1475)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at com.android.systemui.shade.NotificationPanelViewController$ConfigurationListener.onThemeChanged(NotificationPanelViewController.java:4586)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at com.android.systemui.shade.NotificationPanelViewController.onThemeChanged(NotificationPanelViewController.java:3738)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.CentralSurfacesImpl$19.onThemeChanged(CentralSurfacesImpl.java:3394)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.ConfigurationControllerImpl.onConfigurationChanged(ConfigurationControllerImpl.kt:141)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at com.android.systemui.SystemUIApplication.onConfigurationChanged(SystemUIApplication.java:458)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.ConfigurationController.performConfigurationChanged(ConfigurationController.java:265)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.ConfigurationController.handleConfigurationChangedInner(ConfigurationController.java:239)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:157)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:132)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:6582)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:46)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8705)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
12-24 13:24:40.748 23159 23159 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
12-24 13:24:40.750  1667 23295 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
12-24 13:24:40.750  1667  4428 W ActivityManager: Process com.android.systemui has crashed too many times, killing! Reason: crashed quickly
12-24 13:24:40.887  1667  3079 I ActivityManager: Process com.android.systemui (pid 23159) has died: pers PERU
```

### Screenshots or videos

> This was recorded using scrcpy, so the output froze after the crash

https://github.com/user-attachments/assets/901ecb0b-3405-4f82-9003-d117acdb515d

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on risingOS channel for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nivlafx** [comment]
Thanks for the report, resolved here

https://github.com/RisingOS-staging/android_frameworks_base_new/commit/6e1232cf6c1e989562a415d32c517713bfbc6b0d
