### ISSUE TITLE
bug: Spoofing settings activity crashes

### ISSUE THREAD

**Issue by joshuah345** [RisingTechOSS/issue_tracker#61]
### Issue type

Source code related

### Device

Redmi Note 12 Pro 5G (rubyx)

### risingOS version

risingOS 6.x

### Exact version / Build date

6.0 - Dec 24 2024

### Bug description

Spoofing settings cannot be opened.

### Steps to reproduce

1. Go to personalization -> toolbox -> spoofing

### Relevant log (logcat/build log)

```shell
12-24 15:37:13.196  7141  7141 E AndroidRuntime: FATAL EXCEPTION: main
12-24 15:37:13.196  7141  7141 E AndroidRuntime: Process: com.android.settings, PID: 7141
12-24 15:37:13.196  7141  7141 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.Preference.setOnPreferenceChangeListener(androidx.preference.Preference$OnPreferenceChangeListener)' on a null object reference
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4048)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8705)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.Preference.setOnPreferenceChangeListener(androidx.preference.Preference$OnPreferenceChangeListener)' on a null object reference
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.rising.settings.fragments.Spoof.onCreate(Spoof.java:111)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3095)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:516)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:274)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2152)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2047)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:778)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:724)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.settings.SettingsActivity.launchSettingFragment(SettingsActivity.java:515)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.settings.SettingsActivity.createUiFromIntent(SettingsActivity.java:324)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:283)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:9002)12-24 15:37:13.196  7141  7141 E AndroidRuntime: FATAL EXCEPTION: main
12-24 15:37:13.196  7141  7141 E AndroidRuntime: Process: com.android.settings, PID: 7141
12-24 15:37:13.196  7141  7141 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.Preference.setOnPreferenceChangeListener(androidx.preference.Preference$OnPreferenceChangeListener)' on a null object reference
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4048)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4235)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:112)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:174)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:109)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:81)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2636)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8705)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.preference.Preference.setOnPreferenceChangeListener(androidx.preference.Preference$OnPreferenceChangeListener)' on a null object reference
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.rising.settings.fragments.Spoof.onCreate(Spoof.java:111)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:3095)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:516)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:274)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2152)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2047)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1990)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executePendingTransactions(FragmentManager.java:778)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:724)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.settings.SettingsActivity.launchSettingFragment(SettingsActivity.java:515)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.settings.SettingsActivity.createUiFromIntent(SettingsActivity.java:324)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:283)
12-24 15:37:13.196  7141  7141 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:9002)
```

### Screenshots or videos

https://github.com/user-attachments/assets/b1eba496-4a91-48f5-8fdf-772e8be64dd4

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on risingOS channel for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by nivlafx** [comment]
Thanks for the report

Fixed here

https://github.com/RisingOS-staging/android_packages_apps_Personalizations/commit/d74c20b1833cfed73730a53e94acd50ccf6bbfe6
