### ISSUE TITLE
bug: Holding home button crashes SystemUI

### ISSUE THREAD

**Issue by joshuah345** [RisingTechOSS/issue_tracker#65]
### Issue type

User interface

### Device

Redmi Note 12 Pro 5G (rubyx)

### risingOS version

risingOS 6.x

### Exact version / Build date

6.0 - Dec 24 2024

### Bug description

When holding the home button either with 2 or 3 button navigation, SystemUI crashes.

### Steps to reproduce

1. Go to settings -> system -> gestures -> navigation mode
2. switch to 2 or 3 button navigation
3. hold the home button

### Relevant log (logcat/build log)

```shell
12-25 21:37:37.564 21081 21081 E AndroidRuntime: FATAL EXCEPTION: main
12-25 21:37:37.564 21081 21081 E AndroidRuntime: Process: com.android.systemui, PID: 21081
12-25 21:37:37.564 21081 21081 E AndroidRuntime: java.lang.ClassCastException: com.google.android.systemui.assist.OpaLayout cannot be cast to com.android.systemui.navigationbar.buttons.KeyButtonView
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at com.android.systemui.navigationbar.NavigationBar.onHomeLongClick(NavigationBar.java:1444)
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at com.android.systemui.navigationbar.NavigationBar.lambda$new$2(NavigationBar.java:467)
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at com.android.systemui.navigationbar.NavigationBar.$r8$lambda$zY6mSQB2R28kIk6-vWzi6hNheNA(NavigationBar.java:0)
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at com.android.systemui.navigationbar.NavigationBar$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8705)
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
12-25 21:37:37.564 21081 21081 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

### Screenshots or videos

> Doesn't actually freeze, this is due to using scrcpy

https://github.com/user-attachments/assets/6802a8cc-dcef-43da-96b1-dfdb08197e4c

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on risingOS channel for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by joshuah345** [comment]
fixed with https://github.com/RisingTechOSS/android_frameworks_base_new/commit/7e39bc51d2d20660f11c42714c0bf31a123740dd
