### ISSUE TITLE
Freeze when use gesture swipe up

### ISSUE THREAD

**Issue by alexeei** [RisingTechOSS/issue_tracker#70]
### Issue type

User interface

### Device

lmi

### risingOS version

risingOS 6.x

### Exact version / Build date

6.0/2024-12-27

### Bug description

When use 3rd party launcher (may be in ortus also, don't check), after unlock screen with FOD, when open some app, for example settings and then use gesture swipe up from bottom of the screen for return to the main page of launcher, screen don't react on swipe, only react on swipe from top, which show QS, from right to left and from bottom to up not works.  Happened randomly. 

### Steps to reproduce

Step1 Set gesture navigation mode without pill Unlock screen Step 2 Open some app

### Relevant log (logcat/build log)

```shell
12-19 00:18:46.635 16784 16784 D RecentsView: applyLoadPlan - taskGroups: [type=1 task1=[id=21 windowingMode=1 user=0 lastActiveTime=1947449] null task2=null, type=1 task1=[id=22 windowingMode=1 user=0 lastActiveTime=2028186] null task2=null, type=1 task1=[id=20 windowingMode=1 user=0 lastActiveTime=2075620] null task2=null, type=1 task1=[id=24 windowingMode=1 user=0 lastActiveTime=2088841] null task2=null, type=1 task1=[id=25 windowingMode=1 user=0 lastActiveTime=2217597] null task2=null, type=1 task1=[id=23 windowingMode=1 user=0 lastActiveTime=2230241] null task2=null]
12-19 00:18:46.643 16784 16784 D OverviewActionsView: updateForGroupedTask() called with: isGroupedTask = [false], canSaveAppPair = [false]
12-19 00:18:46.643 16784 16784 D OverviewActionsView: updateActionButtonsVisibility() called: showSingleTaskActions = [true], showGroupActions = [false]
12-19 00:18:46.645 16784 16784 D StateManager: goToState - fromState: Normal, toState: Background, partial trace:
12-19 00:18:46.645 16784 16784 D StateManager: 	at com.android.quickstep.BaseActivityInterface$DefaultAnimationFactory.initBackgroundStateUI(BaseActivityInterface.java:228)
12-19 00:18:46.645 16784 16784 D StateManager: 	at com.android.quickstep.LauncherActivityInterface.prepareRecentsUI(LauncherActivityInterface.java:132)
12-19 00:18:46.645 16784 16784 D StateManager: 	at com.android.quickstep.AbsSwipeUpHandler.lambda$onLauncherStart$6(AbsSwipeUpHandler.java:581)
12-19 00:18:46.645 16784 16784 D StateManager: onStateTransitionStart - state: Background
12-19 00:18:46.645 16784 16784 D BaseDepthController: mSurface is null and mCurrentBlur is: 60
12-19 00:18:46.646 16784 16784 D StateManager: onStateTransitionEnd - state: Background
12-19 00:18:46.656 16784 16784 D RecentsView: onGestureAnimationStart - runningTasks: [[id=23 windowingMode=1 user=0 lastActiveTime=2042157] null]
12-19 00:18:46.656 16784 16784 D RecentsView: showCurrentTask - runningTasks: [[id=23 windowingMode=1 user=0 lastActiveTime=2042157] null]
12-19 00:18:46.656  2518  3618 I InputDispatcher: Channel [Gesture Monitor] swipe-up (server) is stealing input gesture for device 3 from [c5eb5c1 org.outline.android.client/org.outline.android.client.MainActivity, [Gesture Monitor] edge-swipe]
12-19 00:18:46.656 16784 16784 D OverviewActionsView: updateForGroupedTask() called with: isGroupedTask = [false], canSaveAppPair = [false]
12-19 00:18:46.656 16784 16784 D OverviewActionsView: updateActionButtonsVisibility() called: showSingleTaskActions = [true], showGroupActions = [false]
12-19 00:18:46.657 16784 18898 W OmniJawsClient: queryWeather while disabled
12-19 00:18:46.660 16784 16784 I TopTaskTracker: onTaskMovedToFront: (moved taskInfo to front) taskId=7, baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000100 cmp=com.android.launcher3/.uioverrides.QuickstepLauncher }
12-19 00:18:46.666 16784 16784 D BaseDepthController: setSurface:
12-19 00:18:46.666 16784 16784 D BaseDepthController: 	mWaitingOnSurfaceValidity: false
12-19 00:18:46.666 16784 16784 D BaseDepthController: 	mSurface: Surface(name=com.android.launcher3/com.android.launcher3.uioverrides.QuickstepLauncher)/@0xf478ff3
12-19 00:18:46.678  2822  2830 V WindowManagerShell: onTransitionReady(transaction=10814727659275)
12-19 00:18:46.678  2822  2858 V WindowManagerShell: onTransitionReady (#159) android.os.BinderProxy@4ee4834: {id=159 t=TO_FRONT f=0x80 trk=0 r=[0@Point(0, 0)] c=[{WCT{android.window.IWindowContainerToken$Stub$Proxy@3746b59} m=TO_FRONT f=SHOW_WALLPAPER|MOVE_TO_TOP leash=Surface(name=Task=1)/@0xfacc65d sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0 taskParent=-1},{WCT{android.window.IWindowContainerToken$Stub$Proxy@11d031e} m=TO_BACK f=NONE leash=Surface(name=Task=23)/@0x9eefbd2 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0 taskParent=-1},{null m=TO_FRONT f=IS_WALLPAPER leash=Surface(name=WallpaperWindowToken{e0cc947 token=android.os.Binder@74ce4c8})/@0x1e764a3 sb=Rect(0, 0 - 1080, 2400) eb=Rect(0, 0 - 1080, 2400) d=0}]}
12-19 00:18:46.678  2822  2858 V WindowManagerShell: Playing animation for (#159) android.os.BinderProxy@4ee4834@0
12-19 00:18:46.678  2822  2858 V WindowManagerShell:  try firstHandler com.android.wm.shell.recents.RecentsTransitionHandler@3746ca3
```

### Solution

Solved with lock by press power button and unlock again. 

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on risingOS channel for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by alexeei** [comment]
Some additions, as i'm checked, gestures and touches of screen seems stop working after this (or same) events (also saw it in other logcat):
12-30 18:31:40.676  1839  3238 I InputDispatcher: Channel af26fd6 UdfpsControllerOverlay (server) is stealing input gesture for device 4 from [67dcf20 NotificationShade, [Gesture Monitor] swipe-up, [Gesture Monitor] edge-swipe]
12-23 14:40:58.914  1810  2237 I InputDispatcher: Channel [Gesture Monitor] swipe-up (server) is stealing input gesture for device 5 from [recents_animation_input_consumer, [Gesture Monitor] edge-swipe]
12-23 14:39:11.405  1810 11530 I InputDispatcher: Channel c497b44 UdfpsControllerOverlay (server) is stealing input gesture for device 5 from [f7b6916 NotificationShade]
12-23 14:40:22.218  1810  9794 I InputDispatcher: Channel [Gesture Monitor] edge-swipe (server) is stealing input gesture for device 5 from [8cf0a18 com.android.settings/com.android.settings.Settings$GestureNavigationSettingsActivity, [Gesture Monitor] swipe-up]
12-23 14:40:50.369  1810 29370 I InputDispatcher: Channel [Gesture Monitor] swipe-up (server) is stealing input gesture for device 5 from [recents_animation_input_consumer, [Gesture Monitor] edge-swipe]
12-21 22:24:50.556  1822  2437 I InputDispatcher: Channel [Gesture Monitor] edge-swipe (server) is stealing input gesture for device 3 from [973a1ec com.android.settings/com.android.settings.SubSettings, [Gesture Monitor] swipe-up]

**Comment by alexeei** [comment]
I'm temporary switch to other ROM because of this bug, today i'll install Rising again and test if issue still here for me, if here, may be it's device issue, then i';; close ticket.
