### ISSUE TITLE
bug: Device auto soft reboot after usage with 1-2 days

### ISSUE THREAD

**Issue by Rsyd58** [RisingTechOSS/issue_tracker#71]
### Issue type

Other

### Device

Xiaomi Redmi 5 Plus (vince)

### risingOS version

risingOS 6.x

### Exact version / Build date

6.1/2024-12-30

### Bug description

After use with 1 untill 2 days, device facing soft reboot

### Steps to reproduce

Step 1: Use RisingOS after 1 - 2 days
Step 2: Use Device as daily driver
Step 3: Sometime, Device facing soft reboot

### Relevant log (logcat/build log)

```shell
--------- beginning of crash
12-31 17:13:28.584  1567  1663 E AndroidRuntime: *** FATAL EXCEPTION IN SYSTEM PROCESS: android.io
12-31 17:13:28.584  1567  1663 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: n > dst.length - dstBegin. n=36, dst.length=0dstBegin=0
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at java.lang.String.getChars(String.java:1064)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.internal.util.FastXmlSerializer.append(FastXmlSerializer.java:116)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.internal.util.FastXmlSerializer.append(FastXmlSerializer.java:140)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.internal.util.FastXmlSerializer.startDocument(FastXmlSerializer.java:370)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.internal.util.XmlSerializerWrapper.startDocument(XmlSerializerWrapper.java:65)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at android.app.ApplicationStartInfo.writeToProto(ApplicationStartInfo.java:757)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.server.am.AppStartInfoTracker$AppStartInfoContainer.writeToProto(AppStartInfoTracker.java:1323)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.server.am.AppStartInfoTracker.lambda$persistProcessStartInfo$6(AppStartInfoTracker.java:964)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.server.am.AppStartInfoTracker.$r8$lambda$7DS3ZbB_AMlhcLWvh_IF7h9sndg(AppStartInfoTracker.java:0)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.server.am.AppStartInfoTracker$$ExternalSyntheticLambda2.apply(R8$$SyntheticClass:0)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.server.am.AppStartInfoTracker.forEachPackageLocked(AppStartInfoTracker.java:741)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.server.am.AppStartInfoTracker.persistProcessStartInfo(AppStartInfoTracker.java:956)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.server.am.AppStartInfoTracker$$ExternalSyntheticLambda4.run(R8$$SyntheticClass:0)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:85)
12-31 17:13:28.584  1567  1663 E AndroidRuntime: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
12-31 17:13:28.744  2104  2104 E AndroidRuntime: FATAL EXCEPTION: main
12-31 17:13:28.744  2104  2104 E AndroidRuntime: Process: com.android.systemui, PID: 2104
12-31 17:13:28.744  2104  2104 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
12-31 17:13:29.273  2305  2305 E AndroidRuntime: FATAL EXCEPTION: main
12-31 17:13:29.273  2305  2305 E AndroidRuntime: Process: com.android.phone, PID: 2305
12-31 17:13:29.273  2305  2305 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
12-31 17:13:29.279 28641  4844 E AndroidRuntime: FATAL EXCEPTION: Thread-1320
12-31 17:13:29.279 28641  4844 E AndroidRuntime: Process: com.netmod.syna:services, PID: 28641
12-31 17:13:29.279 28641  4844 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
12-31 17:13:29.436  5738 28946 E AndroidRuntime: FATAL EXCEPTION: Chrome_ProcessLauncherThread
12-31 17:13:29.436  5738 28946 E AndroidRuntime: Process: com.android.chrome, PID: 5738
12-31 17:13:29.436  5738 28946 E AndroidRuntime: DeadSystemException: The system died; earlier logs will point to the root cause
```

### Additional context

This Bug only happen in RisingOS not LineageOS so, I think is source related issue.
*I Builded with same device tree, vendor tree, and kernel tree with LineageOS 22.x

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on risingOS channel for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Rsyd58** [comment]
This is also happened with my first build RisingOS 6.0

**Comment by eun0115** [comment]
can you drop your dt/vt/kt here? we maintainers didnt got that issues

**Comment by Rsyd58** [comment]
> can you drop your dt/vt/kt here? we maintainers didnt got that issues

Device Tree | https://github.com/Rsyd58/android_device_xiaomi_vince branch 15
Vendor Tree | https://github.com/Rsyd58/android_vendor_xiaomi_vince branch 15
Kernel Tree | https://github.com/Rsyd58/android_kernel_xiaomi_vince branch 13-NKSU
