### ISSUE TITLE
Using horizontal mode results in a crash (High priority)

### ISSUE THREAD

**Issue by Mato52** [RisingTechOSS/issue_tracker#8]
### Issue type

Feature not working as intended

### Device

Motorola edge 30 ultra (eqs)

### risingOS version

risingOS 2.x

### Exact version / Build date

5.0(Open Beta)/2024-08-10

### Bug description

Whenever an app is using the landscape/horizontal mode the system appears to crash

### Steps to reproduce

1. Launch an app with landscape mode (aka any horizontal game or a full screen YouTube video)

### Relevant log (logcat/build log)

```shell
http://www.fileconvoy.com/dfl.php?id=g51739dcdfd3851071000558404aeb48d4c27268013
Download link lasts for 21 days
```

### Screenshots or videos

http://www.fileconvoy.com/dfl.php?id=g5151dc58122a12fd1000558405dacc8cbce20aa91d

Download link lasts for 21 days

### Additional context

Sorry if the links seem suspicious, but I couldn't find any other way to upload the files.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on risingOS channel for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Mato52** [comment]
More logs, different device https://t.me/RisingOS_news/1310?comment=172899

**Comment by Mato52** [comment]
Other eqs logs https://t.me/edge30ultraroms/6214

**Comment by Mato52** [comment]
Possible culprit logs according to @davigamer987
```
08-12 13:20:32.414 E/AndroidRuntime(8961): FATAL EXCEPTION: main
08-12 13:20:32.414 E/AndroidRuntime(8961): Process: com.android.systemui, PID: 8961
08-12 13:20:32.414 E/AndroidRuntime(8961): java.lang.NullPointerException: Attempt to invoke virtual method 'void androidx.constraintlayout.motion.widget.MotionLayout.jumpToState(int)' on a null object reference
08-12 13:20:32.414 E/AndroidRuntime(8961):   at com.android.keyguard.KeyguardPasswordView.updateConstraints(KeyguardPasswordView.java:160)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at com.android.keyguard.KeyguardSecurityViewFlipper.updateConstraints(KeyguardSecurityViewFlipper.java:92)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at com.android.keyguard.KeyguardSecurityViewFlipperController.updateConstraints(KeyguardSecurityViewFlipperController.java:184)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at com.android.keyguard.KeyguardSecurityContainerController$5.onOrientationChanged(KeyguardSecurityContainerController.java:391)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at com.android.systemui.statusbar.phone.ConfigurationControllerImpl.onConfigurationChanged(ConfigurationControllerImpl.kt:145)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at com.android.systemui.SystemUIApplication.onConfigurationChanged(SystemUIApplication.java:449)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.app.ConfigurationController.performConfigurationChanged(ConfigurationController.java:246)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:220)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.app.ConfigurationController.handleConfigurationChanged(ConfigurationController.java:131)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:6522)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.app.servertransaction.ConfigurationChangeItem.execute(ConfigurationChangeItem.java:48)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:231)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.app.servertransaction.TransactionExecutor.executeTransactionItems(TransactionExecutor.java:152)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:93)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2595)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.os.Handler.dispatchMessage(Handler.java:107)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.os.Looper.loopOnce(Looper.java:232)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.os.Looper.loop(Looper.java:317)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at android.app.ActivityThread.main(ActivityThread.java:8594)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at java.lang.reflect.Method.invoke(Native Method)
08-12 13:20:32.414 E/AndroidRuntime(8961):   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
```

**Comment by Mato52** [comment]
The latest build pushed by @davigamer987 seems to fix the issue, so I guess it's good
